

name: 🙏🏻 Lint Test
on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
